import = ["/home/nisidabay/.config/alacritty/dracula.toml"]

[window]
opacity = 0.7

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 13.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

