[window]
opacity = 0.8

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 14.0


[font.bold]
family = "FantasqueSansMono"
style = "Bold"

[font.bold_italic]
family = "FantasqueSansMono"
style = "Bold Italic"

[font.italic]
family = "FantasqueSansMono"
style = "Italic"

[font.normal]
family = "FantasqueSansMono"
style = "Regular"

[font.offset]
x = 0
y = 12
