#!/bin/bash

# dwmblocks script to display available package updates
TERMINAL="alacritty"

# Get the count of available package updates
packages=$(checkupdates | wc -l)

# Set the icon based on the number of available packages
if [ "$packages" -gt 0 ]; then
    icon="📦"
    color="#ff0000"  # Red color for available packages
else
    icon="✔️"
    color="#00ff00"  # Green color for no available packages
fi

# Display the package count with the appropriate icon
echo -e "$icon $packages"

# Handle different mouse button clicks
case "$BLOCK_BUTTON" in
    1) 
        # Display a notification with the available package count
        notify-send "Available packages:" "$packages"
        ;;
    2|3) 
        # Update the system using pacman
        setsid -f "$TERMINAL" -e sh -c 'echo "Running update"; ~/bin/mysudo sudo pacman -Syyu; read -p "Press enter to continue"'
        wait $!  # Wait for the background process to finish
        notify-send "Pacman updated" "The system has been updated"
        ;;
esac

