--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/nisidabay/Pictures/current_bg_image.png"

-- Special
background="#050507"
foreground="#c0c0c1"
cursor="#c0c0c1"

-- Colors
color0="#050507"
color1="#3e4236"
color2="#943b21"
color3="#446557"
color4="#9f773f"
color5="#155466"
color6="#1b7675"
color7="#828283"
color8="#434345"
color9="#535848"
color10="#C64F2D"
color11="#5B8774"
color12="#D59F55"
color13="#1D7188"
color14="#259E9D"
color15="#c0c0c1"
