# Shell variables
# Generated by 'wal'
wallpaper="/home/nisidabay/Pictures/current_bg_image.png"

# Special
background='#050507'
foreground='#c0c0c1'
cursor='#c0c0c1'

# Colors
color0='#050507'
color1='#3e4236'
color2='#943b21'
color3='#446557'
color4='#9f773f'
color5='#155466'
color6='#1b7675'
color7='#828283'
color8='#434345'
color9='#535848'
color10='#C64F2D'
color11='#5B8774'
color12='#D59F55'
color13='#1D7188'
color14='#259E9D'
color15='#c0c0c1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
