#!/bin/sh
#
# A dwm_bar function that shows the current artist, track, position, duration, and status from cmus
# Joe Standring <git@joestandring.com>
# GNU GPLv3

# Dependencies: cmus
if  ! command -v cmus >/dev/null 2>&1; then
    echo "cmus not installed"
    exit 1
fi

dwm_cmus () {
    SEP1=" | "
    if ps -C cmus > /dev/null; then
        CMUSDATA=$(cmus-remote -Q)
        ARTIST=$(echo "$CMUSDATA" | grep -w '^tag artist' | awk '{gsub("tag artist ", "");print}')
        TRACK=$(echo "$CMUSDATA" | grep -w '^tag title' | awk '{gsub("tag title ", "");print}')
        STATUS=$(echo "$CMUSDATA" | grep -w '^status' | awk '{gsub("status ", "");print}')
        SHUFFLE=$(echo "$CMUSDATA" | grep -w '^set shuffle' | awk '{gsub("set shuffle ", "");print}')

            if [ "$STATUS" = "playing" ]; then
                STATUS="▶"
            else
                STATUS="⏸"
            fi

            if [ "$SHUFFLE" = "true" ]; then
                SHUFFLE=" 🔀"
            else
                SHUFFLE=""
            fi
        
        printf "%s%s %s - %s " "$SEP1" "$STATUS" "$ARTIST" "$TRACK"
        printf "%s%s\n" "$SHUFFLE" "$SEP1"
    else
        printf "%s%s\n" "⏹️" "$SEP1"
    fi
}


case $BLOCK_BUTTON in
    1) "$TERMINAL" -e cmus ;;  
    2) pgrep cmus | xargs kill;;
	3) notify-send "🎵 Music module" "\- Shows cmus song playing.
- Left click opens cmus.
- Middle click stop it."
esac

dwm_cmus
