#!/bin/sh
TERMINAL="alacritty"
case $BLOCK_BUTTON in

    1) notify-send "💽 Backup disk usage" "$(df -h /dev/sdb1 | awk 'NR >1 {print $4}')" ;;
    2) setsid -f "$TERMINAL" -e ncdu "/mnt/sata";;
    3) notify-send "💽 Disk module " "\- Shows backup disk usage

- Click to show disk usage.
- Middle click to open ncdu." ;;
esac

df -h /dev/sdb1 | awk 'NR >1 {print "💽", $4}'
