github.com:
    oauth_token: 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
    user: nisidabay
    git_protocol: https
    users:
        nisidabay:
            oauth_token: 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
